# Generated by Django 3.0 on 2019-12-16 13:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191213_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_picture',
            field=models.ImageField(blank=True, upload_to=api.models.task_directory_path, verbose_name='Task picture'),
        ),
    ]
